In [88]:
import numpy as np

In [1]:
import torch
pt = torch.load('D:\\Xinshuai\\daima\\XProNet-main\\files\\mimic_cxr\\init_prototypes.pt')

In [2]:
pth= torch.load('D:\\Xinshuai\\daima\\XProNet-main\\files\\mimic_cxr\\test_label_from_ve.pth')

In [3]:
import pickle
file_read = open('D:\\Xinshuai\\daima\\XProNet-main\\files\\mimic_cxr\\labels_14.pickle','rb')
pick=pickle.load(file_read)

In [4]:
pt

tensor([[ 0.5621,  0.4456,  0.7422,  ...,  0.6398,  0.3468,  0.3127],
        [ 0.5584,  0.4466,  0.7213,  ...,  0.1272, -0.3341, -0.1327],
        [ 0.6104,  0.4542,  0.7094,  ...,  0.1084, -0.2678,  0.0973],
        ...,
        [ 0.6121,  0.4361,  0.7103,  ...,  0.4767,  0.6268, -0.1317],
        [ 0.6228,  0.4645,  0.7078,  ...,  0.1069, -0.2614,  0.0832],
        [ 0.4956,  0.3758,  0.7737,  ...,  0.3271,  0.2272,  0.5368]],
       dtype=torch.float64)

In [5]:
pth

{'427446c1-881f5cce-85191ce1-91a58ba9-0a57d3f5': array([False, False, False, False, False, False,  True,  True,  True,
         True,  True, False,  True,  True]),
 'abea5eb9-b7c32823-3a14c5ca-77868030-69c83139': array([False, False, False, False, False,  True,  True, False,  True,
        False, False, False,  True, False]),
 '18f0fd6d-f513afc9-e4aa8de2-bc5ac0d6-ea3daaff': array([False, False, False, False, False,  True,  True, False, False,
        False, False, False,  True,  True]),
 '7d5ef12b-34d86e32-207566d6-d5ed6f02-cd868f2c': array([False, False, False, False, False, False,  True, False,  True,
        False, False, False,  True, False]),
 'eab11c59-32a5b9b8-b8d335fa-ce06c5fa-5bde0499': array([False, False, False,  True, False, False, False, False, False,
         True, False, False,  True,  True]),
 '6e511483-c7e1601c-76890b2f-b0c6b55d-e53bcbf6': array([False, False, False,  True, False, False, False, False,  True,
         True,  True, False,  True,  True]),
 'e5ba5704-ce2f0

In [7]:
import json

In [8]:
path=open('D:\\Xinshuai\\mimic\\Tre-label\\Pleural Effusion\\HF_train.json')
js=json.load(path)

In [9]:
js

{'0': ['  Interval resolution of previously seen mild pulmonary edema with trace bilateral pleural effusions.'],
 '1': [' New mild pulmonary edema with persistent small bilateral pleural effusions.'],
 '10': [' bilateral pleural effusions.'],
 '100': [' though a pericardial effusion cannot be completely excluded.'],
 '1000': [' COPD with tiny bilateral effusions.'],
 '1001': [' Opacification at the left lung base likely represents small left pleural effusion with adjacent atelectasis.'],
 '1002': [' Low lung volumes with unchanged bibasilar atelectasis and pleural effusion.'],
 '1003': [' There is no evidence for the presence of pleural effusion on the frontal and the lateral radiograph.'],
 '1004': [' There is no evidence for the presence of pleural effusion on the frontal and the lateral radiograph.'],
 '1005': [' pulmonary edema and bilateral pleural effusions.'],
 '1007': [' Bilateral pleural effusions are noted.'],
 '1008': [' There is a moderate left effusion that is increased in

In [11]:
from lxml import etree
import json
import os
from collections import Counter
import random



def dict_save_json(dict, file_name):
    with open('{}'.format(file_name), 'w') as file_position:
        json.dump(dict, file_position)
    print('save json file: {}'.format(file_name))


if __name__ == '__main__':
    frontal_image_path = 'D:\\Xinshuai\\mimic\\Tre_total_CXR\\'
    report_path='D:\\Xinshuai\\mimic\\Tre_total_Report_tre_Last\\Cardiomegaly\\'
    # The image name
    frontal_names_lst = []
    # The image number after CXR
    frontal_num_lst = []
    report_name_lst=[]
    report_con=[]
    # one_sentence_impression = False
    json_dict = {}
    json_dict_train = {}
    json_dict_test = {}
    # The image dataset with only frontal views is selected manually.
    for frontal_image_name in os.listdir(frontal_image_path):
        frontal_names_lst.append(str(frontal_image_name).split(".")[0])

    for name in os.listdir(report_path):
        xml_file = os.path.join(report_path, name)
        report_name_lst.append(str(name).split(".")[0])
        with open(xml_file,'r') as report:
            report_con.append(report.readlines())

    for image_name in range(0,len(frontal_names_lst)):
        for report_name in range(0,len(report_name_lst)):
            if report_name_lst[report_name]==frontal_names_lst[image_name]:
                json_dict[frontal_names_lst[image_name]] = report_con[image_name]
                if random.random() < 0.3 and len(json_dict_test.keys()) < 3000:
                    json_dict_test[frontal_names_lst[image_name]] = report_con[image_name]
                else:
                    json_dict_train[frontal_names_lst[image_name]] = report_con[image_name]
    
    if len(json_dict_test.keys()) != 3000:
        print("Please run this program AGAIN!")
    assert len(json_dict_test.keys()) == 3000

    print('The number of complete radiology reports with the frontal view in total:', len(json_dict.keys()))
    print('The number of complete radiology reports with the frontal view in training set:', len(json_dict_train.keys()))
    print('The number of complete radiology reports with the frontal view in testing set:', len(json_dict_test.keys()))

    # gnerate json file from the dictionary
    dict_save_json(json_dict, "D:\\Xinshuai\\mimic\\json\\C\\C_total.json")
    dict_save_json(json_dict_train, "D:\\Xinshuai\\mimic\\json\\C\\C_total_train.json")
    dict_save_json(json_dict_test, "D:\\Xinshuai\\mimic\\json\\C\\C_total_test.json")


The number of complete radiology reports with the frontal view in total: 15655
The number of complete radiology reports with the frontal view in training set: 12655
The number of complete radiology reports with the frontal view in testing set: 3000
save json file: D:\Xinshuai\mimic\json\C\C_total.json
save json file: D:\Xinshuai\mimic\json\C\C_total_train.json
save json file: D:\Xinshuai\mimic\json\C\C_total_test.json


In [14]:
import pandas as pd
df=pd.read_csv('D:\\Xinshuai\\mimic\\MIMIC_IV\\tre_entil.csv')

In [32]:
pick_={}
for i in range(len(df)):
    pick_[str(i)]=df[i:i+1][['Cardiomegaly','Edema','Pleural Effusion']].values[0]

In [28]:
df[0:1][['Cardiomegaly','Edema','Pleural Effusion']].values[0]

array([1., 1., 1.])

In [41]:
with open('D:\\Xinshuai\\mimic\\labels_3_pickle\\labels_3.pickle', 'wb') as f:
    pickle.dump(pick_,f)

In [42]:
file_read = open('D:\\Xinshuai\\mimic\\labels_3_pickle\\labels_3.pickle','rb')
pick1=pickle.load(file_read)

In [53]:
label_000=[]
label_001=[]
label_010=[]
label_011=[]
label_100=[]
label_101=[]
label_110=[]
label_111=[]

In [54]:
df

study_id  subject_id                                      dicom_id  \
0      52468723    10032409  34f23866-9991ce93-f6f7495b-66e153ef-b675a214   
1      52729515    10032409  e00f67fe-2d13a03e-adabba21-b1bd2559-bf6a4211   
2      58140535    10032409  dfe5bd7c-62b3017d-f4376788-350156fe-c874652d   
3      54278093    10035631  5289286b-f35e9847-42128310-27e9a9b5-7d5471e2   
4      50369509    10037928  7fb7f551-f194f40f-5f0dc014-cfe132c5-0f5f3da1   
...         ...         ...                                           ...   
15650  54829612    10024982  4642211b-b3cec9a0-84833d67-14ba3bd8-9e153ce3   
15651  54829612    10024982  eb5010b1-3f708e8c-07675d8f-7e32dc4c-e3a8d83f   
15652  57368861    10024982  b47eb172-69fb1128-274e9add-37204072-c8ae8bdc   
15653  58575944    10024982  983e4044-1df93a05-d6b02476-fb356e40-aba20c38   
15654  58575944    10024982  b10b26a3-8d2f5ac0-44d2379a-6405cad2-12ef5312   

       Cardiomegaly  Edema  Pleural Effusion  
0               1.0    1.0               1.0  
1               1.0    1.0               1.0  
2               1.0    1.0               1.0  
3               0.0    0.0               0.0  
4               0.0    0.0               0.0  
...             ...    ...               ...  
15650           1.0    1.0               1.0  
15651           1.0    1.0               1.0  
15652           1.0    1.0               1.0  
15653           1.0    1.0               1.0  
15654           1.0    1.0               1.0  

[15655 rows x 6 columns]

In [67]:
label_000=(df[(df['Cardiomegaly']==0.0) & (df['Edema']==0.0) & (df['Pleural Effusion']==0.0)]).index.tolist()
label_001=(df[(df['Cardiomegaly']==0.0) & (df['Edema']==0.0) & (df['Pleural Effusion']==1.0)]).index.tolist()
label_010=(df[(df['Cardiomegaly']==0.0) & (df['Edema']==1.0) & (df['Pleural Effusion']==0.0)]).index.tolist()
label_011=(df[(df['Cardiomegaly']==0.0) & (df['Edema']==1.0) & (df['Pleural Effusion']==1.0)]).index.tolist()
label_100=(df[(df['Cardiomegaly']==1.0) & (df['Edema']==0.0) & (df['Pleural Effusion']==0.0)]).index.tolist()
label_101=(df[(df['Cardiomegaly']==1.0) & (df['Edema']==0.0) & (df['Pleural Effusion']==1.0)]).index.tolist()
label_110=(df[(df['Cardiomegaly']==1.0) & (df['Edema']==1.0) & (df['Pleural Effusion']==0.0)]).index.tolist()
label_111=(df[(df['Cardiomegaly']==1.0) & (df['Edema']==1.0) & (df['Pleural Effusion']==1.0)]).index.tolist()

In [104]:
feature_000=[]
feature_001=[]
feature_010=[]
feature_011=[]
feature_100=[]
feature_101=[]
feature_110=[]
feature_111=[]

In [105]:
feature=[feature_000
,feature_001
,feature_010
,feature_011
,feature_100
,feature_101
,feature_110
,feature_111]

In [106]:
for i in range(len(label)):
    for k in range(len(label[i])):
        path_img='D:\\Xinshuai\\mimic\\Tre_total_CXR_feature\\'+str(label[i][k])
        path_txt_c='D:\\Xinshuai\\mimic\\Tre_total_Report_tre_Last\\Bert-feature\\C\\'+str(label[i][k])
        f_imp=np.loadtxt(path_img).tolist()
        f_txt_c=np.loadtxt(path_txt_c).tolist()
        f_tem=f_imp+f_txt_c
        feature[i].append(f_tem)

In [163]:
init_prototypes=[]

In [164]:
for i in range(8):
    init_prototypes_=[]
    tem=pd.DataFrame(feature[i][0])
    for k in range(len(feature[i])-1):
        tem.insert(tem.shape[1],str(k+1),feature[i][k+1])
    tem=tem.T
    for i in range(2816):
        init_prototypes_.append(sum(tem[i])/len(tem[i]))
    init_prototypes.append(init_prototypes_)

In [167]:
init_prototypes

tensor([[ 0.5666,  0.4429,  0.7546,  ..., -0.5492, -0.1852, -0.1767],
        [ 0.5608,  0.4363,  0.7595,  ..., -0.5653, -0.1811, -0.1579],
        [ 0.5585,  0.4417,  0.7543,  ..., -0.5725, -0.1422, -0.1492],
        ...,
        [ 0.5601,  0.4339,  0.7606,  ..., -0.5205, -0.4167, -0.1221],
        [ 0.5608,  0.4363,  0.7536,  ..., -0.5267, -0.3815, -0.1226],
        [ 0.5571,  0.4318,  0.7573,  ..., -0.4729, -0.4118, -0.0813]])

In [166]:
init_prototypes=torch.tensor(init_prototypes)

In [168]:
init_prototypes

tensor([[ 0.5666,  0.4429,  0.7546,  ..., -0.5492, -0.1852, -0.1767],
        [ 0.5608,  0.4363,  0.7595,  ..., -0.5653, -0.1811, -0.1579],
        [ 0.5585,  0.4417,  0.7543,  ..., -0.5725, -0.1422, -0.1492],
        ...,
        [ 0.5601,  0.4339,  0.7606,  ..., -0.5205, -0.4167, -0.1221],
        [ 0.5608,  0.4363,  0.7536,  ..., -0.5267, -0.3815, -0.1226],
        [ 0.5571,  0.4318,  0.7573,  ..., -0.4729, -0.4118, -0.0813]])

In [169]:
torch.save(init_prototypes,'D:\\Xinshuai\\mimic\\init_prototypes.pt')

In [172]:
f=open('D:\\Xinshuai\\mimic\\json\\C\\C_total_test.json')
test=json.load(f)

In [206]:
pth

{'427446c1-881f5cce-85191ce1-91a58ba9-0a57d3f5': array([False, False, False, False, False, False,  True,  True,  True,
         True,  True, False,  True,  True]),
 'abea5eb9-b7c32823-3a14c5ca-77868030-69c83139': array([False, False, False, False, False,  True,  True, False,  True,
        False, False, False,  True, False]),
 '18f0fd6d-f513afc9-e4aa8de2-bc5ac0d6-ea3daaff': array([False, False, False, False, False,  True,  True, False, False,
        False, False, False,  True,  True]),
 '7d5ef12b-34d86e32-207566d6-d5ed6f02-cd868f2c': array([False, False, False, False, False, False,  True, False,  True,
        False, False, False,  True, False]),
 'eab11c59-32a5b9b8-b8d335fa-ce06c5fa-5bde0499': array([False, False, False,  True, False, False, False, False, False,
         True, False, False,  True,  True]),
 '6e511483-c7e1601c-76890b2f-b0c6b55d-e53bcbf6': array([False, False, False,  True, False, False, False, False,  True,
         True,  True, False,  True,  True]),
 'e5ba5704-ce2f0

In [250]:
cc=df[df.index==test_[i]][['Cardiomegaly','Edema','Pleural Effusion']].replace(1.0,'True').replace(0.0,'False').values[0].tolist()

In [251]:
cc=np.array(cc)

In [252]:
cc

array(['True', 'False', 'True'], dtype='<U5')

In [235]:
test_label={}
for i in range(len(test_)):
    test_label[str(test_[i])]=df[df.index==test_[i]][['Cardiomegaly','Edema','Pleural Effusion']].replace(1.0,'True').replace(0.0,'False').values[0]

In [254]:
test_label['10']

array(['True', 'False', 'True'], dtype=object)

In [258]:
torch.save(test_label,'D:\\Xinshuai\\mimic\\test_label.pt')

In [257]:
test_label

{'10': array(['True', 'False', 'True'], dtype=object),
 '10004': array(['True', 'True', 'True'], dtype=object),
 '10006': array(['True', 'True', 'True'], dtype=object),
 '10011': array(['True', 'True', 'True'], dtype=object),
 '10013': array(['True', 'True', 'False'], dtype=object),
 '10016': array(['False', 'False', 'False'], dtype=object),
 '10017': array(['True', 'True', 'False'], dtype=object),
 '10018': array(['True', 'False', 'False'], dtype=object),
 '10026': array(['False', 'True', 'False'], dtype=object),
 '10027': array(['False', 'True', 'True'], dtype=object),
 '10033': array(['True', 'True', 'True'], dtype=object),
 '10036': array(['True', 'True', 'True'], dtype=object),
 '10037': array(['True', 'True', 'True'], dtype=object),
 '10038': array(['True', 'True', 'True'], dtype=object),
 '1004': array(['True', 'False', 'False'], dtype=object),
 '10044': array(['True', 'True', 'True'], dtype=object),
 '10045': array(['True', 'True', 'True'], dtype=object),
 '10053': array(['True